# Generated by Django 6.0.1 on 2026-02-04 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(choices=[('ONE_TO_ONE', 'One to One'), ('GROUP', 'Group')], max_length=20)),
                ('category', models.CharField(blank=True, choices=[('FARMER', 'Farmer'), ('SELLER', 'Seller'), ('INFLUENCER', 'Influencer')], max_length=20, null=True)),
                ('person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(max_length=100)),
                ('attendees_count', models.PositiveIntegerField(blank=True, null=True)),
                ('business_potential', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='meetings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
