# Generated by Django 5.2.6 on 2026-02-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occamy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("ADMIN", "Admin"), ("DISTRIBUTOR", "Distributor")],
                max_length=20,
                null=True,
            ),
        ),
    ]
