# Generated by Django 5.2.6 on 2026-02-07 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receiver_name", models.CharField(max_length=255)),
                (
                    "receiver_category",
                    models.CharField(
                        choices=[
                            ("FARMER", "Farmer"),
                            ("SELLER", "Seller"),
                            ("INFLUENCER", "Influencer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("TRIAL", "Trial"),
                            ("DEMO", "Demo"),
                            ("FOLLOW_UP", "Follow Up"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_given", models.DateField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "given_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
